ci: cloud-monitor: Add AWS cloud monitor job
This commit adds a job that monitors the AWS cloud to the cloud monitor
workflow.

Signed-off-by: Stephanos Ioannidis <root@stephanos.io>

diff --git a/.github/workflows/cloud-monitor.yml b/.github/workflows/cloud-monitor.yml
--- a/.github/workflows/cloud-monitor.yml
+++ b/.github/workflows/cloud-monitor.yml
@@ -9,6 +9,81 @@ on:
   - cron: '*/10 * * * *'
 
 jobs:
+  # AWS Cloud Monitor Job
+  aws-monitor:
+    name: AWS Cloud Monitor
+    runs-on: ubuntu-22.04
+
+    env:
+      DISCORD_INFRA_MONITOR_WEBHOOK: "${{ secrets.DISCORD_INFRA_MONITOR_WEBHOOK }}"
+      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
+      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+      AWS_DEFAULT_REGION: "us-east-2"
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v4
+
+    - name: Install Kubernetes command line tools
+      run: |
+        curl -LO https://dl.k8s.io/release/v1.23.0/bin/linux/amd64/kubectl
+        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+
+    - name: Check environment
+      run: |
+        jq --version
+        aws --version
+        kubectl version --client=true
+
+    - name: Check EKS cluster nodegroups
+      continue-on-error: true
+      run: |
+        nodeGroupNames=$(aws eks list-nodegroups --cluster-name zephyr-alpha | jq -r '.nodegroups[]')
+        isFailed="no"
+
+        for nodeGroupName in $nodeGroupNames; do
+          nodeGroup=$(aws eks describe-nodegroup --cluster-name zephyr-alpha --nodegroup-name $nodeGroupName)
+          nodeGroupStatus=$(echo "$nodeGroup" | jq -r '.nodegroup.status')
+
+          if [ "$nodeGroupStatus" != 'ACTIVE' ]; then
+            .github/log.sh ERROR "aws: zephyr-alpha: Found nodegroup '${nodeGroupName}' with inactive status."
+            isFailed="yes"
+          fi
+        done
+
+        if [ "$isFailed" = "yes" ]; then
+          exit 911
+        fi
+
+    - name: Get EKS cluster configuration
+      run: |
+        aws eks update-kubeconfig --name zephyr-alpha --kubeconfig config
+        echo "KUBECONFIG=${PWD}/config" >> $GITHUB_ENV
+
+    - name: Check Kubernetes nodes
+      run: |
+        kubectl get nodes
+        nodeList=$(kubectl get nodes -o json)
+
+        notReadyCount=$(echo "$nodeList" | jq -r '
+          [
+            .items[].status.conditions[] |
+            select(.type == "Ready") |
+            select(.status | not)
+          ] | length')
+
+        if [ "$notReadyCount" -gt "0" ]; then
+          .github/log.sh ERROR "aws: zephyr-alpha: Found ${notReadyCount} node(s) with not-ready status."
+          exit 911
+        fi
+
+    - name: Report failure
+      if: failure()
+      run: |
+        jobUrl="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+        .github/log.sh ERROR "aws: Cloud monitor job ${{ github.run_id }} failed.\n${jobUrl}"
+
+  # Centrinix Cloud Monitor Job
   cnx-monitor:
     name: Centrinix Cloud Monitor
     runs-on: ubuntu-22.04
@@ -68,7 +143,7 @@ jobs:
           ] | length')
 
         if [ "$nonActiveCount" -gt "0" ]; then
-          .github/log.sh ERROR "Found ${nonActiveCount} server(s) with non-active status."
+          .github/log.sh ERROR "cnx: Found ${nonActiveCount} server(s) with non-active status."
           exit 911
         fi
 
@@ -87,7 +162,7 @@ jobs:
           ] | length')
 
         if [ "$incompleteCount" -gt "0" ]; then
-          .github/log.sh ERROR "Found ${incompleteCount} nodegroup(s) with incomplete status."
+          .github/log.sh ERROR "cnx: zephyr-ci: Found ${incompleteCount} nodegroup(s) with incomplete status."
           exit 911
         fi
 
@@ -114,6 +189,12 @@ jobs:
           ] | length')
 
         if [ "$notReadyCount" -gt "0" ]; then
-          .github/log.sh ERROR "Found ${notReadyCount} node(s) with not-ready status."
+          .github/log.sh ERROR "cnx: zephyr-ci: Found ${notReadyCount} node(s) with not-ready status."
           exit 911
         fi
+
+    - name: Report failure
+      if: failure()
+      run: |
+        jobUrl="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+        .github/log.sh ERROR "cnx: Cloud monitor job ${{ github.run_id }} failed.\n${jobUrl}"
